// Copyright true 2022. All Rights Reserved.
// Node module: suy-frontend
// This file is licensed under the Creative Commons Attribution Non Commercial No Derivatives 2.0

import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Components from '../layout/Components'

const Home: NextPage = () => {
  
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Components/>
    </div>
  )
}

export default Home
